securityContext:
  runAsUser: 1000
  fsGroup: 1001
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::992382613070:role/cert-manager
  name: cert-manager
  namespace: cert-manager
  automountServiceAccountToken: true




## Set up the service account
## Use helm template to generate the cert-manager manifests and then apply them with kubectl apply

# helm template cert-manager jetstack/cert-manager \                                                                                                            [21/10/24 18:18:23]
#   --namespace cert-manager \
#   --version v1.15.3 \
#   --set installCRDs=true \
#   -f cert-manager.values.yaml | kubectl apply -f -

## cert-manager logs
# kubectl logs -l app=cert-manager -n cert-manager